name: Deploy to Dokku - production

on: [push, workflow_dispatch]

env:
  DOKKU_HOST: 'paas.hivenet.xyz'
  DOKKU_APP_NAME: 'simple-servicetag-generator'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ env.DOKKU_HOST }}
          app-name: ${{ env.DOKKU_APP_NAME }}
